### ISSUE TITLE
k8s version to 1.1

### ISSUE THREAD

**Issue by mattfarina** [deis/helm#139]
I noticed that help is using k8s version `2e5a3cfbc62e4a63423f43f2e6d5723806569b17`. This isn't tied to any tagged release version. It's somewhere between releases.

Is there a version of k8s that should be used since it is versioned?

**Comment by technosophos** [comment]
_sigh_ We wanted to go with 1.1.0... but we had a little problem with k8s build stability. So I pinned it on basically the one version I knew was working.

/me hangs head in shame.

**Comment by technosophos** [comment]
So I updated to k8s 1.1.1, and there's a package version conflict that I am now trying to trace. Things compile fine (based on resolution of nested Godeps), but I'm getting this at runtime:

```
helm info alpine                                                                                                                                                                                     2 ↵
helm flag redefined: log_dir
panic: helm flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc820074060, 0x19a4698, 0xc8201a9b00, 0x8e7850, 0x7, 0x9a96a0, 0x2f)
	/usr/local/Cellar/go/1.5.1/libexec/src/flag/flag.go:776 +0x46b
flag.(*FlagSet).StringVar(0xc820074060, 0xc8201a9b00, 0x8e7850, 0x7, 0x0, 0x0, 0x9a96a0, 0x2f)
	/usr/local/Cellar/go/1.5.1/libexec/src/flag/flag.go:679 +0xc7
flag.(*FlagSet).String(0xc820074060, 0x8e7850, 0x7, 0x0, 0x0, 0x9a96a0, 0x2f, 0xc8201a9af0)
	/usr/local/Cellar/go/1.5.1/libexec/src/flag/flag.go:692 +0x83
flag.String(0x8e7850, 0x7, 0x0, 0x0, 0x9a96a0, 0x2f, 0x62237b)
	/usr/local/Cellar/go/1.5.1/libexec/src/flag/flag.go:699 +0x5f
github.com/golang/glog.init()
	/Users/mattbutcher/Code/Go/src/github.com/golang/glog/glog_file.go:41 +0x13e
k8s.io/kubernetes/pkg/util/fielderrors.init()
	/Users/mattbutcher/Code/Go/src/k8s.io/kubernetes/pkg/util/fielderrors/fielderrors.go:208 +0x4f
k8s.io/kubernetes/pkg/labels.init()
	/Users/mattbutcher/Code/Go/src/k8s.io/kubernetes/pkg/labels/selector.go:682 +0x56
k8s.io/kubernetes/pkg/api.init()
	/Users/mattbutcher/Code/Go/src/k8s.io/kubernetes/pkg/api/unversioned.go:106 +0x6b
k8s.io/kubernetes/pkg/apis/experimental.init()
	/Users/mattbutcher/Code/Go/src/k8s.io/kubernetes/pkg/apis/experimental/types.go:542 +0x40
github.com/deis/helm/manifest.init()
	/Users/mattbutcher/Code/Go/src/github.com/deis/helm/manifest/manifest.go:201 +0x68
github.com/deis/helm/chart.init()
	/Users/mattbutcher/Code/Go/src/github.com/deis/helm/chart/chartfile.go:63 +0x4f
github.com/deis/helm/action.init()
	/Users/mattbutcher/Code/Go/src/github.com/deis/helm/action/update.go:140 +0x65
main.init()
	/Users/mattbutcher/Code/Go/src/github.com/deis/helm/helm.go:392 +0x45

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1

goroutine 20 [chan receive]:
github.com/deis/helm/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0xcf2cc0)
	/Users/mattbutcher/Code/Go/src/github.com/deis/helm/vendor/github.com/golang/glog/glog.go:879 +0x67
created by github.com/deis/helm/vendor/github.com/golang/glog.init.1
	/Users/mattbutcher/Code/Go/src/github.com/deis/helm/vendor/github.com/golang/glog/glog.go:410 +0x297```

**Comment by technosophos** [comment]
Fixed
